#!/usr/bin/env python3
"""Expand 6 short concept essays to meet generous length requirements. Idempotent."""
import json

with open('/home/user/TheosophicalAlchemyDB/data/prototype_data.json') as f:
    data = json.load(f)

concept_updates = {
    51: """Sublimation (from Latin *sublimare*, to elevate) is simultaneously a fundamental laboratory operation and a philosophically charged metaphor in alchemical tradition. The operation designates the direct passage of a solid substance into vapor under heat — bypassing the liquid phase — followed by condensation as a purified solid on cooler surfaces. In laboratory practice, it was applied to sulfur, arsenic, mercury sublimate, and sal ammoniac (ammonium chloride), which volatilize readily and condense as purified crystalline deposits. The physical display is visually compelling: matter dissolves into air and rematerializes, transformed, making sublimation one of the most symbolically resonant operations in the alchemical repertoire.

In alchemical philosophy, sublimation represents elevation and purification. What is dense becomes light; the fixed becomes volatile; the earthy becomes aerial. The substance achieves a refined mode of existence without ceasing to be material — the condensed sublimate remains physical but has shed impurities through its passage. This process maps directly onto the spiritual project: the soul, like the sublimed substance, can be elevated without becoming disembodied, purified without ceasing to be particular. Paracelsus (1493-1541) made sublimation central to his physiology: digestion is a sublimation by which the archaeus (the vital principle governing each organ) refines alimentary matter into specific bodily substances.

The Neoplatonic resonance of sublimation is evident in the word's etymology: *sub limen* (below the threshold) or *sub limine* (carrying upward to the lintel). For Renaissance Neoplatonists who read Ficino and Pico, the operation figured the soul's natural aspiration toward its divine source — a tendency encoded in matter's own behavior under transformative fire.

Michael Maier (1568-1622) deployed sublimation imagery extensively in the Atalanta Fugiens (1618), where ascending vapors in multiple emblems represent the volatile mercury-principle rising toward consummation. De Jong's source analysis (Michael Maier's Atalanta Fugiens, 1969) traces the genealogy of sublimation symbolism through Pseudo-Geber's Summa Perfectionis and the Rosarium Philosophorum. Daniel Stolcius's Viridarium Chymicum (1624) shows the distillation apparatus as emblem: heat below corresponds to devotion, ascending vapor to spirit's elevation, condensed sublimate to achieved transformation. Szulakowska (Art and Alchemy, 2006) identifies the sublimation emblem as one of the key images through which seventeenth-century alchemists encoded the unity of material operation and spiritual philosophy.""",
    
    60: """Multiplicity and Return (Latin *multiplicatio* and *regressus*) designates the philosophical problem and alchemical possibility at the heart of Neoplatonic alchemy: if all things proceed from the One through a cascade of descending multiplicity, can the many return to the One, and under what conditions? For alchemical philosophy in the Neoplatonic tradition — from Plotinus (c.204-270 CE) through Proclus (412-485 CE) and into Renaissance Neoplatonism — creation is understood as emanation from divine unity producing an ordered hierarchy of beings, each level less unified and more multiple than the level above. The return (*epistrophe*) is the mirror movement: the created being's natural aspiration toward its source, the reintegration of multiplicity into unity.

For alchemical philosophy, this framework has immediate practical implications. The prima materia represents the lowest level of multiple differentiation: matter as such, before any specific form. The Philosopher's Stone represents the achieved return — a substance of maximal unity and potency, capable of multiplying its power through projection onto lesser substances. The Stone's property of transmuting base metals while remaining unchanged makes it a material image of the Neoplatonic One, which gives of itself to all things while remaining undiminished.

The multiplication of the Stone (*multiplicatio lapidis*) is a specific late-stage alchemical operation: once achieved, the Stone can be projected onto mercury or other metals in increasing quantities, each projection multiplying its power. This material multiplication images the philosophical creativity of the One's emanation. Mike Zuber (Spiritual Alchemy, 2007) analyzes how the spiritual alchemy tradition understood this multiplication: in Böhme's system, the soul's return to divine ground enriches both the returning soul and the divine source — a multiplication of divine life through creaturely participation.

The concept connects to the broader question of unity and diversity in hermetic cosmology. Ficino's translations of the Enneads (1492) made the Neoplatonic framework available to Renaissance alchemists, and the identification of the alchemical opus with the soul's return to its divine source became a standard interpretive strategy. Joscelyn Godwin (The Theosophical Enlightenment, 1994) traces how this identification developed through the seventeenth and eighteenth centuries from theological metaphor into practical mystical program.""",

    56: """Gender and Alchemy encompasses both a historical subject (the gender dynamics of alchemical practice) and a conceptual category (the gendering of alchemical principles and operations). These dimensions intertwine: the philosophical framework informed social practice, and social realities of women's participation shaped how philosophical categories were understood.

At the philosophical level, alchemy inherited from Aristotelian natural philosophy a gendered cosmology: active principle (male, solar, hot, dry) and passive principle (female, lunar, cold, moist) combine to produce all natural substances. This is not mere metaphor but systematic natural philosophy in which gender pervades all of nature. In alchemical theory, sulfur (active, fixed, solar) is consistently figured as masculine; mercury (volatile, receptive, lunar) as feminine. The opus requires their conjunction, figured throughout alchemical literature as marriage (hieros gamos), sexual union, and mutual transformation.

The gender imagery of the alchemical process — the king and queen, the hermetic hermaphrodite, the nursing mother, the virgin sophia — performs philosophical work. It encodes a cosmological claim: that the most fundamental dynamic in nature is the productive tension between complementary principles. Michael Maier's Atalanta Fugiens (1618) makes this gender dynamic its explicit subject: the hero's pursuit of the fleet-footed Atalanta (who is simultaneously the feminine principle evading capture, the volatile mercury, and the divine wisdom that cannot be grasped by force) structures the entire fifty-emblem sequence. Maier's portrayal of Atalanta as active agent — she sets the terms of the chase, she chooses the apples — makes the feminine principle something other than passive matter to be worked upon.

At the historical level, women's participation in alchemy ranged from laboratory practice to theoretical production to institutional leadership. Mary the Jewess (fl. c. 1st-3rd century CE) is credited in Arabic sources with inventing several key laboratory apparatus. Jane Lead (1624-1704) was the most prolific English spiritual alchemist of the seventeenth century and founder of the Philadelphian Society. Mary Anne Atwood (1817-1910) wrote the most comprehensive account of spiritual alchemy in English. Despite this participation, women faced systematic barriers: exclusion from university medical faculties, lack of access to expensive laboratory materials, and cultural suspicion of women claiming philosophical authority.

Szulakowska (Art and Alchemy, 2006) analyzes the gender dynamics of Rosicrucian emblem books, noting that feminine figures in Maier's work — Atalanta, Lady Sapientia, the nursing figure — are active agents, not passive objects. Zuber (Spiritual Alchemy, 2007) traces how spiritual alchemy's gendered cosmology shaped women practitioners' self-understanding and justified their philosophical authority: if the feminine principle is the receptive, nurturing, transformative force at the heart of the opus, women have a distinctive access to its inner meaning.""",

    55: """Interior Work (Latin *opus internum*) designates the alchemical tradition's recognition that the most fundamental transformation in the opus occurs not in the laboratory vessel but in the practitioner's consciousness, perception, and spiritual orientation. The phrase contrasts with *opus externum* (the external work — the laboratory operations of heating, dissolving, coagulating) to insist that genuine alchemical achievement requires a corresponding interior transformation in the practitioner.

The clearest early systematic articulation appears in Paracelsus (1493-1541), who insisted that the physician-alchemist who had not undergone interior purification would fail in laboratory work: his corrupted perception would misread what he observed. The archaeus — the vital principle governing each organ — could only be understood by a practitioner whose own archaeus was properly oriented. This is not mysticism imported into natural philosophy but a specific epistemological claim: the knowing subject's inner state is causally relevant to knowing rightly.

Johann Arndt (1555-1621) developed the interior work in explicitly Lutheran terms in Vier Bücher vom wahren Christentum (1606-1610): the soul's purification through stages analogous to the alchemical opus — nigredo (spiritual despair, recognition of sin), albedo (divine consolation, beginning of union), rubedo (achieved union, glorification) — is the genuine work of Christian piety. Arndt made this arc a standard framework for Lutheran mystical theology, influencing every subsequent Protestant spiritual alchemist from Böhme to Lead to Atwood.

Jacob Böhme's contribution was his insistence on the interior work's experiential immediacy: the transformation he described was not theoretical but directly encountered in contemplative practice. His descriptions of the soul's journey through Angst, desire, fire, and light draw on the same alchemical vocabulary as laboratory practice but locate it entirely within the practitioner's consciousness. Mike Zuber (Spiritual Alchemy, 2007) argues that Böhme's primary influence on the spiritual alchemy tradition consists in providing a vivid first-person phenomenological account of interior work that subsequent practitioners could use as a map of their own experience.

Heinrich Khunrath (1560-1605) synthesized laboratory and interior work with particular visual elegance in his Amphitheatrum Sapientiae Aeternae (1595/1609): his famous frontispiece places the oratory-laboratory with the site of prayer directly adjacent to the furnace, insisting that both spaces are required and neither is sufficient alone. Szulakowska (Art and Alchemy, 2006) emphasizes that Khunrath's image is a genuine epistemological claim: the interior orientation of the practitioner and the external operations of the laboratory are two aspects of a single transformative work.""",

    57: """Color Symbolism in Alchemy is operational, not ornamental: the sequence of colors observed in the heated vessel — black (nigredo), white (albedo), yellow (citrinitas), red (rubedo) — provides the primary evidence by which the practicing alchemist tracks the progress of the opus. The colors are not symbols projected onto neutral processes from without but observable appearances of the transforming substance, read by a trained eye as signs of specific philosophical-chemical states.

The classical four-stage color sequence derives from ancient alchemy. Zosimos of Panopolis (c. 300 CE) describes the stages using color terms; the tradition was transmitted through Byzantine and Arabic alchemy into Latin. By the high medieval period, the four colors were the primary framework for the opus's temporal structure: nigredo (blackening, putrefaction, death), albedo (whitening, purification, the moon), citrinitas (yellowing, a transitional stage increasingly omitted in later tradition), and rubedo (reddening, achievement of solar gold, the completed stone).

The colors operate simultaneously at material, psychological, and theological registers. At the material level, observed color changes correlate with specific chemical processes: initial blackening corresponds to carbonization of organic matter; subsequent whitening to formation of white sulfides or oxides; reddening to red sulfides such as cinnabar (mercuric sulfide) or realgar (arsenic sulfide). C.G. Jung's Psychology and Alchemy (1944) mapped the color stages onto stages of psychological transformation, though Jung's interpretation is contested by historians of science (see Lawrence Principe and William Newman, Alchemy Tried in the Fire, 2002). At the theological level, Protestant alchemists like Arndt and Böhme read the color stages as figures of the soul's journey through despair, consolation, and glorification.

Michael Maier's Atalanta Fugiens (1618) deploys color symbolism with philosophical precision: emblems associated with whiteness feature lunar imagery, Diana, or the nursing mother; those associated with redness feature solar imagery, the crowned king, or the phoenix. H.M.E. De Jong (1969) traces Maier's color vocabulary to its sources in medieval Latin alchemy, demonstrating that his symbolic system rests on specific textual precedents in Pseudo-Geber and the Rosarium Philosophorum.

The peacock's tail (cauda pavonis) — a brief prismatic display of multiple colors at a transitional moment between albedo and rubedo — represents the most visually dramatic color event in the entire sequence. Its appearance in numerous emblem books marks it as a privileged and dangerous site: beautiful but unstable, it signals proximity to the goal while warning against premature celebration. Szulakowska (Art and Alchemy, 2006) analyzes how alchemical emblem books use color as systematic code: the same image in different colors carries different alchemical meanings, and a sequence of colors through an emblem book traces the opus's progression.""",

    53: """Correspondence (Latin *correspondere*, to respond mutually) in the alchemical and hermetic traditions designates the fundamental principle that entities at different levels of reality are structurally related — that the macrocosm (the great world of celestial and natural phenomena) and the microcosm (the small world of the human being, or of the individual substance in the alchemical vessel) mirror each other and respond to each other's states. This is the principle condensed in the Emerald Tablet's formulation: "As above, so below; as below, so above; to accomplish the miracle of one thing."

The doctrine of correspondences has roots in multiple ancient traditions: Stoic cosmology (the *sympatheia* of all things in the pneuma-unified cosmos), Neoplatonic emanationism (each lower level reflects and participates in the higher), and ancient divinatory practice (celestial events signify and influence terrestrial ones). In Hermeticism as transmitted through the Corpus Hermeticum (2nd-3rd century CE) and recovered by Ficino's translation (1463), correspondences are built into the fabric of created reality: metals correspond to planets (gold to sun, silver to moon, copper to Venus, iron to Mars, tin to Jupiter, lead to Saturn, mercury to Mercury), colors to stages of the opus, human organs to celestial bodies.

For practical alchemy, the doctrine is operational. If gold corresponds to the sun, the timing of alchemical operations should be coordinated with solar cycles; if the human body corresponds to the macrocosm, then transformations worked in the vessel have their reflection in the practitioner's physiology and consciousness. Paracelsus (1493-1541) made correspondences the foundation of his medical theory: disease results from a disturbance in the correspondence between the microcosm (human body) and macrocosm (planetary and elemental world); treatment restores correspondence through remedies chosen for their correspondence to the diseased organ's planetary ruler.

Michael Maier's Atalanta Fugiens (1618) employs the correspondence doctrine as its organizing metaphysical framework: the Ovidian narrative, alchemical operations, musical fugues, and philosophical emblems all correspond to each other and to the same underlying reality. H.M.E. De Jong (1969) demonstrates that Maier's elaborate cross-referencing system — mythology, chemistry, astrology, and music all illuminating the same events from different angles — is made possible by the correspondence doctrine. To know the myth is to know the chemistry; to hear the music is to experience the transformation.

Szulakowska (Art and Alchemy, 2006) emphasizes that correspondence is not a belief in magical causation but a philosophical claim about the structure of reality: the world is not a collection of independent entities but an ordered whole in which every part reflects the whole. This claim, while archaic in form, anticipated features of later scientific holism — the recognition that systems exhibit emergent properties that cannot be understood by analyzing parts in isolation."""
}

updated = 0
for concept in data['concepts']:
    cid = concept.get('id')
    if cid in concept_updates:
        concept['essay'] = concept_updates[cid]
        updated += 1

print(f"Updated {updated} concept essays")
for concept in data['concepts']:
    if concept.get('id') in concept_updates:
        print(f"  ID {concept.get('id')}: {concept.get('name','')} -> {len(concept.get('essay',''))} chars")

with open('/home/user/TheosophicalAlchemyDB/data/prototype_data.json', 'w') as f:
    import json as _json
    _json.dump(data, f, indent=2, ensure_ascii=False)
print("Saved.")
