"""Final patch: expand all remaining thin entries."""
import json, pathlib

DB = pathlib.Path("site/data/prototype_data.json")

FIGURE_PATCHES = {
"Johann Valentin Andreae": """Johann Valentin Andreae (1586–1654) was a Lutheran theologian, polymath, and social reformer who almost certainly authored the Chemical Wedding of Christian Rosenkreutz (1616)—the most literary of the three Rosicrucian manifestos—and who was deeply involved in the Tübingen circle from which all three manifestos emerged. His later disavowal of the Rosicrucian movement as a 'ludibrium' (jest or game) has generated sustained scholarly debate: was the disavowal sincere, or a protective rhetorical strategy in the face of the controversy the manifestos provoked?

Carlos Gilly's archival research at the Herzog August Bibliothek Wolfenbüttel has demonstrated that Andreae knew Tobias Hess (the central figure in the manifesto circle), copied the Fama Fraternitatis in manuscript, and composed the Chemical Wedding as a young student at Tübingen around 1605. The Chemical Wedding's distinctive literary quality—its seven days structured as an initiatory narrative rich with alchemical allegory, chivalric romance conventions, and Protestant eschatology—reflects Andreae's broad humanist education and his engagement with Paracelsian philosophy.

Andreae's more programmatic works include Christianopolis (1619), a utopian narrative describing an ideal Christian community dedicated to learning, craft, and devotion, and the Reipublicae Christianopolitanae Descriptio. These works reveal Andreae's genuinely reformist agenda: the transformation of society through Christian education, practical craft, and scientific study—a program continuous with the Rosicrucian manifestos' call for universal reform even if Andreae later distanced himself from the movement the manifestos had spawned. Donald Dickson and Gilly's research situates Andreae as a central figure in the transmission of Protestant reformist ideas through the early seventeenth century, connecting the Rosicrucian episode to the broader history of Protestant social utopianism.""",

"Robert Fludd": """Robert Fludd (1574–1637), English physician and Hermetic philosopher, is the most important British representative of the Hermetic-alchemical tradition in the early seventeenth century. His massive illustrated cosmology, Utriusque Cosmi Historia (1617–1621), presents a comprehensive account of the macrocosm and microcosm organized around the Hermetic principle of correspondences, with elaborate engraved diagrams—including the famous world monochord—depicting the mathematical relationships between celestial and terrestrial scales.

Fludd was born in Kent, educated at St John's College Oxford, and received his medical degree from Christ Church in 1605. His extensive European travels (c. 1598–1604) brought him into contact with Continental Hermetic and Paracelsian circles, and his subsequent practice as a London physician combined conventional Galenic medicine with Paracelsian remedies and Hermetic philosophy. His defense of the Rosicrucian brotherhood in Apologia Compendiaria (1616) and Tractatus Apologeticus (1617)—written before, not after, the Utriusque Cosmi—established him as the Rosicrucian movement's most prominent English defender.

Fludd's controversies with Johannes Kepler (over the nature of mathematical-physical explanation) and Marin Mersenne (over the legitimacy of occult philosophy) placed him at the center of the early seventeenth-century debate between Hermetic and mechanistic natural philosophy. Joscelyn Godwin's Robert Fludd: Hermetic Philosopher and Surveyor of Two Worlds (1979) remains the essential English-language study. Urszula Szulakowska's analysis of Fludd's iconographic program in The Alchemy of Light demonstrates how his diagrams encode a complete Neoplatonic philosophy of light, situating the Utriusque Cosmi within the visual tradition of Hermetic cosmological diagramming rather than within early modern natural science.""",

"Ashmole, Elias": """Elias Ashmole (1617–1692) was the foremost collector of alchemical manuscripts in seventeenth-century England, whose Theatrum Chemicum Britannicum (1652)—the first comprehensive anthology of English alchemical poetry—established the English alchemical tradition as a serious subject of antiquarian study. His vast library of alchemical, astrological, and magical manuscripts, now preserved in the Bodleian Library as the Ashmolean Collection, is the primary archival resource for the history of English alchemy.

Ashmole trained as a lawyer but devoted his life to antiquarianism, heraldry, and the occult sciences. He joined a Freemason lodge in Warrington in 1646—the earliest documented record of operative Masonic initiation in England—and his Masonic connection illustrates the interpenetration of alchemical, Hermetic, and Masonic traditions in the mid-seventeenth century. His connections extended to Simon Forman's astrological manuscripts, to the circle of William Backhouse (who reportedly whispered the secret of the philosopher's stone to Ashmole on his deathbed in 1651), and to the broader network of practical astrologers and alchemists in Civil War and Restoration England.

The Theatrum Chemicum Britannicum is Ashmole's major scholarly achievement: assembling and annotating the works of Thomas Norton, George Ripley, John Lydgate, Thomas Charnock, and dozens of minor English alchemical poets, with an extensive Prolegomena situating the English tradition within the broader European context. Jennifer Rampling's recent scholarship on the Ashmolean Collection has revealed the depth and sophistication of Ashmole's engagement with alchemical practical traditions, showing that he conducted his own laboratory work alongside his antiquarian researches. Ashmole donated his collection to Oxford in 1677, founding the Ashmolean Museum—the first public museum in England.""",

"Catherine de Medici": """Catherine de Medici (1519–1589), Queen Consort and then Regent of France, was one of the most consequential political figures of the sixteenth century and a significant patron of astrology, alchemy, and occult arts at the French royal court. Her patronage shaped the reception of Hermetic and astrological ideas in France during the period of the Wars of Religion, and her court became a site where Italian Hermetic humanism, French royal astrology, and Paracelsian medicine intersected.

Born into the ruling Medici family of Florence—descendants of Cosimo de' Medici, who had commissioned Ficino's translation of the Corpus Hermeticum—Catherine absorbed the Florentine Neoplatonist and Hermetic tradition from childhood. Her court astrologer Nostradamus (Michel de Nostredame), whose Centuries she patronized, exemplified the continuity of late medieval prophetic and astrological tradition into the sixteenth century. Catherine's interest in alchemy was both practical (she maintained a laboratory at Blois) and political (alchemical gold-making promised relief from perpetual royal financial crisis).

The political and religious crisis of the French Wars of Religion shaped Catherine's engagement with the occult sciences: court astrology, prophecy, and magical practice were resources for navigating a situation of extreme political uncertainty. Keith Cameron and N. M. Sutherland's historiographical work on Catherine's regency situates her patronage of astrology within broader strategies of political management and dynastic survival. For the Hermetic and alchemical portal, Catherine represents the royal court as a site of alchemical patronage—the political economy that made alchemy socially possible, providing the noble and royal support that enabled figures like Paracelsus, Michael Maier (at Rudolf II's court), and John Dee (at Elizabeth's) to pursue their work.""",

"Henry Khunrath": """Heinrich Khunrath (1560–1605)—the correct name; 'Henry' is an anglicization—was a German physician and alchemical philosopher whose Amphitheatrum Sapientiae Aeternae (Amphitheatre of Eternal Wisdom, Hamburg 1595; expanded Hanover 1609) is the most spectacular and philosophically ambitious emblem book of the alchemical and Rosicrucian tradition. Born in Leipzig, Khunrath studied medicine at Basel (MD 1588), establishing himself as a physician in Hamburg and Dresden.

Khunrath's philosophical formation drew on Paracelsian medicine, Hermetic philosophy, Lutheran theology, and Christian Kabbalah. His Warhafftiger Bericht (1597) defended Paracelsian chemical medicine against Galenist critics. The Amphitheatrum synthesizes these commitments into a comprehensive initiatory program: the four circular engraved plates (depicting the laboratorium-oratorium, the stage of philosophical ascent, the hermaphroditic stone, and the divine Word at the center of creation) map the adept's journey from practical laboratory work through philosophical enlightenment to divine union.

Peter Forshaw's comprehensive scholarship—including his doctoral dissertation on Khunrath and multiple articles on the Amphitheatrum's visual program—has established the intellectual context of Khunrath's work, documenting his visit to John Dee in Bremen in 1589 and his connections with the broader network of Hermetic philosophers in late sixteenth-century Germany. Urszula Szulakowska's The Alchemy of Light provides the fullest art-historical analysis of the Amphitheatrum's plates, situating them within the tradition of Neoplatonic light theology and demonstrating how Khunrath's visual program encodes a complete philosophy of divine illumination through alchemical purification.""",

"Symphorien Champier": """Symphorien Champier (c. 1472–c. 1539) was a French physician, humanist, and writer who played a significant role in transmitting Italian Neoplatonism and Hermetic philosophy to French readers in the early sixteenth century. Born in Lyon, he was trained in medicine at Valence and Paris, and served as physician to the Duke of Lorraine. His extensive literary production included medical works, historical chronicles, and philosophical treatises that drew on Ficino's Neoplatonism and the Hermetic tradition.

Champier's medical works—particularly the Myrouel des Apothicaires (1532) and his editions of medical texts—brought Galenic medicine and Paracelsian-adjacent natural philosophy to French readers. His Liber de Quadruplici Vita (1507) synthesized Neoplatonic accounts of the soul's ascent with Christian mystical theology, demonstrating the interpenetration of medical, philosophical, and theological concerns in early sixteenth-century humanism. His Rose de Vie drew on Hermetic cosmology and the macrocosm-microcosm analogy in a vernacular framework accessible to educated lay readers.

Champier's significance for the TheosophicalAlchemyDB lies in his role as a transmitter: he was among the first French writers to engage systematically with Ficino's Neoplatonism, Hermetic texts, and the tradition of natural magic that would shape later French engagement with Paracelsian and Rosicrucian ideas. His Lyon base was a crucial node in the transmission of Italian humanist ideas to northern Europe; Lyon's printing industry and its mercantile connections with Italy made it a natural center for the diffusion of Hermetic texts across the Alps. Brian Copenhaver's work on French Hermetism situates Champier within the network through which Hermetic ideas traveled from Florence to France in the early sixteenth century.""",

"Adam von Bodenstein": """Adam von Bodenstein (1528–1577) was a German physician and the most important early editor and publisher of Paracelsus's writings, responsible for bringing a substantial portion of the Paracelsian corpus into print in the decades following Paracelsus's death. Born in Basel, the son of Andreas Bodenstein von Karlstadt (the radical reformer), Adam studied medicine and became a convinced Paracelsian, dedicating his career to collecting, editing, and defending Paracelsus's unpublished manuscripts.

Bodenstein's editorial work began in the 1560s and produced numerous first editions of Paracelsian texts, including Paracelsus's philosophy of nature, his astronomical and astrological works, and his practical medical writings. His prefaces and dedications provide valuable documentation of the Paracelsian movement's self-understanding in the generation after the master's death, including claims about Paracelsus's divine inspiration and the practical efficacy of his remedies. Bodenstein was also involved in the controversy over Paracelsian medicine, defending iatrochemical remedies against Galenist critics.

Lawrence Principe and William Newman's historiographical work on Paracelsian reception emphasizes the role of editors like Bodenstein in constructing the 'Paracelsian corpus'—a collection that was as much the work of his editors as of Paracelsus himself, since so much was assembled from notes, fragments, and later elaborations. Charles Webster's comprehensive study Paracelsus: Medicine, Magic and Mission at the End of Time (2008) situates Bodenstein within the network of Paracelsian practitioners and reformers who transformed Paracelsus from a controversial physician into the prophet of a new medicine and philosophy. Bodenstein's editorial work was thus not merely scholarly but actively constructive of the Paracelsian tradition that would feed into Rosicrucianism.""",

"Oswald Croll": """Oswald Croll (c. 1563–1609) was a German physician and the most important systematizer of Paracelsian iatrochemical medicine in the generation after Paracelsus's death. His Basilica Chymica (The Chemical Palace, Frankfurt 1609), dedicated to Emperor Rudolf II, became the standard textbook of Paracelsian chemical medicine—widely translated, reprinted, and studied throughout the seventeenth century as the authoritative synthesis of Paracelsian pharmaceutical practice and natural philosophy.

The Basilica's structure is emblematic of Croll's systematic ambitions: a prefatory Admonitory Preface (Praefatio Admonitoria) provides a comprehensive philosophical defense of Paracelsian medicine against Galenist critics, drawing on macrocosm-microcosm theory, Hermetic philosophy, and Protestant providential theology; the main text then presents a practical formulary of chemical medicines organized by their preparation and application. The Preface is one of the most eloquent defenses of the Paracelsian program ever written, and was cited and criticized by subsequent writers throughout the seventeenth century.

Croll's Rudolf II connection is significant: he was physician and chemist to Christian I of Anhalt, who was in the orbit of the Palatine court that would later patronize the Rosicrucian movement. Rudolf's Prague court, where Croll's Basilica was dedicated, was the preeminent center of alchemical patronage in Europe at the turn of the seventeenth century, attracting practitioners including Michael Maier, John Dee, Edward Kelley, and dozens of lesser-known figures. R. J. W. Evans's Rudolf II and His World (1973) provides the essential context for understanding Croll's patronage environment; Lawrence Principe's work on the Paracelsian tradition situates the Basilica Chymica within the broader history of early modern chemical medicine.""",

"Andreas Libavius": """Andreas Libavius (c. 1555–1616) was a German physician and chemist whose Alchemia (1597) is the first comprehensive textbook of chemistry organized according to systematic principles—a work that both drew on the Paracelsian and alchemical traditions and subjected them to critical scrutiny. Libavius accepted iatrochemical medicine and the utility of distillation, calcination, and other chemical operations while rejecting the Paracelsian cosmological framework and the mystical elaborations of figures like Oswald Croll and Heinrich Khunrath.

Libavius's critical stance is historically important: he represents the beginning of the differentiation between 'chemistry' (as practical and theoretical knowledge of substances and their transformations) and 'alchemy' (as mystical, cosmological, or fraudulent gold-making). His critiques targeted Paracelsus's tria prima (as unnecessary speculation), Croll's philosophical preface (as obscurantism), and the Rosicrucian manifestos—Libavius wrote two critical analyses of the Fama Fraternitatis identifying it as spiritually dangerous and philosophically incoherent.

Lawrence Principe and William Newman's revisionist historiography of alchemy engages carefully with Libavius: they acknowledge his importance as a systematizer while challenging the older reading that positioned him as a proto-rationalist liberator of chemistry from alchemical mysticism. Their work shows that the Alchemia still contains numerous alchemical operations and theoretical commitments that later chemists would also abandon; Libavius's critique is partial and targeted rather than comprehensive. Bruce Moran's The Alchemical World of the German Court (1991) situates Libavius within the political economy of German court science, showing how his Gymnasium in Coburg shaped the next generation of physicians and chemical practitioners.""",

"Jābir ibn Ḥayyān (Geber)": """Jābir ibn Hayyān (fl. c. 721–815 CE), known to Latin readers as Geber, is the most important figure in the history of Arabic alchemy and one of the foundational influences on the entire Western alchemical tradition. Whether the historical Jabir was a single person or a composite tradition—the 'Jabirian corpus' contains hundreds of texts with no clear single authorship—the body of work attributed to him established the theoretical and practical foundations of Arabic alchemy.

The Jabirian corpus (Kitab al-Kimya and related texts) advanced the sulphur-mercury theory of metals: all metals are composed of sulphur and mercury (not in their ordinary forms but as philosophical principles) in varying degrees of purity, and transmutation consists in bringing the sulphur-mercury composition of base metals to the degree of purity found in gold and silver. This theory, transmitted to Latin Europe through translations in the twelfth and thirteenth centuries, became the foundational framework for medieval Latin alchemy and persisted into the early modern period in Paracelsian tria prima (which added Salt as a third principle).

William Newman's Gehennical Fire: The Lives of George Starkey, an Alchemist of Newton's Scientific Revolution (1994) traces how the Jabirian sulphur-mercury theory was received and transformed by Latin alchemists, showing that the pseudo-Geber of the fourteenth century (a Latin author who wrote under the Arabic name) generated many of the most practically important medieval alchemical doctrines. Paul Kraus's fundamental Jabir ibn Hayyan: Contribution à l'Histoire des Idées Scientifiques dans l'Islam (1942) remains the essential philological study of the Arabic corpus. For the TheosophicalAlchemyDB, Jabir represents the crucial Arabic transmission link through which ancient Greek and Hellenistic alchemical knowledge was preserved, systematized, and transmitted to the Latin West.""",

"Robert Boyle": """Robert Boyle (1627–1691), famous as the pioneer of modern chemistry and the formulator of Boyle's Law, maintained a far more complex relationship with the alchemical tradition than the standard narrative of scientific rationalization suggests. Lawrence Principe's The Aspiring Adept: Robert Boyle and His Alchemical Quest (1998) demonstrates through archival research in Boyle's unpublished manuscripts that Boyle actively pursued alchemical transmutation research throughout his life, conducting laboratory experiments aimed at preparing the philosopher's stone even as he publicly criticized scholastic and Paracelsian theory in The Sceptical Chymist (1661).

Boyle's public persona—the modernizing experimentalist who replaced 'occult qualities' with mechanical corpuscular philosophy—coexisted with a private practice that included correspondence with alchemical adepts, payment for claimed philosophical gold, and extensive manuscript notes on transmutation experiments. This double life illustrates the complexity of the alchemy-chemistry boundary in the seventeenth century: Boyle did not simply escape from alchemy into modern chemistry but pursued both simultaneously, valuing the practical results that alchemical experimentation might produce even as he rejected the theoretical framework.

Principe's archival work also documents Boyle's correspondence with George Starkey (Eirenaeus Philalethes), whose manuscript notebooks—analyzed in Newman and Principe's Alchemy Tried in the Fire (2002)—reveal a sophisticated laboratory researcher working within the alchemical tradition to produce novel chemical results. Newton's analogous private alchemical practice, documented by Dobbs and Newman, suggests that the relationship between alchemy and early modern natural philosophy was far more symbiotic than the traditional historiography of 'scientific revolution' acknowledged. Boyle thus stands as the pivotal figure through whom alchemy's transition into chemistry must be traced, not its simple replacement.""",
}

CONCEPT_PATCHES = {
"Mercury Philosophical": """Philosophical Mercury (Mercurius Philosophorum) is the second of Paracelsus's three prime principles, designating not ordinary quicksilver but the principle of volatility, fluidity, and communication that pervades all natural substances. As the principle of Mercury, it represents the soul's faculty of communication, the capacity to mediate between fixed and volatile states, and the universal solvent principle that makes all transformations possible.

In the alchemical sulphur-mercury theory—the framework that preceded and shaped Paracelsus's tria prima—Mercury is the volatile, feminine, lunar principle that receives the solar, masculine, fixed Sulphur and produces metals in the earth through their conjunction. The proportion and purity of their combination determines the resulting metal: gold results from the perfect conjunction of pure, cooked sulphur and mercury, while base metals result from impure or disproportionate combinations. This theory, developed by Arabic alchemists and transmitted to Latin Europe by the twelfth century, remained foundational throughout the early modern period.

For spiritual alchemists in the Böhme tradition, Philosophical Mercury corresponds to the soul's communicative and mediating principle—the capacity to receive divine influence and transmit it to the body, to connect the spiritual and material dimensions of the human person. The soul's Mercury must be volatile enough to ascend to divine illumination while retaining its capacity to 'fix' the illumination received and communicate it back into embodied practice. Paracelsus's concept of the archeus—the vital organizing principle in each substance—is sometimes identified with Philosophical Mercury as the intelligent, communicative, directive principle that gives each thing its specific form and character. William Newman and Lawrence Principe's work on Decknamen shows how 'Philosophical Mercury' in specific texts can designate either this theoretical principle or specific laboratory substances—most commonly metallic mercury itself but sometimes other volatile substances—requiring contextual reading to determine which sense is intended.""",

"Calcination": """Calcination is the alchemical and chemical operation of heating a substance in air or flame until it is reduced to a fine powder (calx) by the expulsion of volatile components. Metallurgically, calcination converts metals to metal oxides (lead to lead oxide, iron to iron oxide); pharmaceutically, it was used to prepare mineral medicines by rendering them less toxic and more easily assimilated. In the alchemical sequence, calcination represents the first stage of purification—the reduction of composite matter to its most basic, fixed form prior to dissolution and reconstruction.

In the alchemical interpretation, calcination corresponds to the purification by fire—the burning away of all volatile impurities to leave the pure, fixed Salt (the alchemical body). This is the first operation in many versions of the Great Work, corresponding to the nigredo's initial phase: the destruction of the old form is the necessary precondition for the new. Laboratory descriptions of calcination are precise: specific temperatures, durations, and vessel types produce characteristic calcined products, and the color of the calx (white, red, grey, black) indicates the progress of purification.

Lawrence Principe's laboratory reconstructions of historical alchemical procedures demonstrate that calcination was a key operation in early modern chemistry's development of quantitative analysis: by comparing the weight of a metal before and after calcination, chemists could observe the consistent weight gain that later Antoine Lavoisier explained through the discovery of oxygen. Robert Boyle's investigations of calcination, and his tentative explanations in terms of the addition of 'igneous particles,' illustrate how alchemical calcination practice generated questions that eventually demanded the pneumatic chemistry of the late eighteenth century. The alchemical calcination operation thus stands as a historically important example of how practical laboratory procedures preceded and generated the theoretical frameworks that eventually replaced alchemical natural philosophy.""",

"Quintessence / Quinta Essentia": """The Quintessence (quinta essentia, fifth essence) is in Aristotelian philosophy the celestial element—the substance of which the heavenly spheres are made, perfect, unchanging, and incorruptible, as distinguished from the four terrestrial elements (fire, air, water, earth) that are subject to generation and corruption. In alchemical application, the quintessence is the concentrated, purified essence extracted from a natural substance—the distilled virtue or active principle that contains all the substance's medicinal or transformative power in its most refined form.

Paracelsus transformed the quintessence concept by applying it to practical pharmaceutical preparation: through repeated distillation, the quintessence of a plant or mineral is progressively concentrated until it reaches a state of pure, unchangeable efficacy—a 'celestial' preparation that participates in the incorruptibility of the fifth element. This pharmaceutical quintessence was his alchemical ideal: a medicine so refined it has shed all grossness and operates as a direct expression of the celestial virtue governing the substance.

The quintessence concept connects alchemy to astrology and natural magic: if each terrestrial substance has a celestial correspondent (its planet, its star), then extracting the quintessence of a substance liberates the celestial virtue it contains, making it accessible for medical or magical application. Marsilio Ficino's Three Books on Life (1489) elaborates this in terms of spiritus—the subtle, pneumatic medium between celestial and terrestrial—and recommends preparations aimed at concentrating celestial spirit in medicines. Michael Maier's Atalanta Fugiens encodes the production of the quintessence through several of its emblems, treating the extraction of the 'fifth essence' from the four elements as the key operation by which the philosopher's stone is produced. Urszula Szulakowska's analysis of Maier's emblematic program demonstrates how the quintessence appears as the culmination of the four-element purification sequence.""",

"Magistery / Magister": """The Magistery (magisterium, also magister, 'master') is a term in alchemical and pharmaceutical literature designating a preparation of the highest perfection—the most fully developed, most completely purified form of a substance, capable of operating on other substances to perfect or transform them. In its fullest sense, magisterium designates the philosopher's stone itself as the master medicine and master transforming agent; in more restricted pharmaceutical usage, it designates any preparation brought to the highest possible degree of purity and efficacy through repeated alchemical operations.

The concept reflects the hierarchical thinking of alchemical natural philosophy: just as the sun is the most perfect celestial body (having perfectly cooked and purified gold in the earth), and gold is the most perfect metal, the magisterium is the most perfect preparation—the culmination of the Great Work in pharmaceutical or transformative form. This perfection is both qualitative (purity of essence) and operative (capacity to project that quality onto other substances), which is why the philosopher's stone can project its transformative quality onto base metals and onto the human body in medicine.

In early modern pharmaceutical practice, the term magisterium was applied to preparations that claimed to concentrate the active virtue of a substance through alchemical operations: magistery of bismuth, magistery of coral, magistery of pearl were common pharmaceutical products. Robert Boyle critiqued these preparations in The Sceptical Chymist, questioning whether the claimed alchemical concentration actually occurred or whether the 'magistery' was merely a fine suspension or solution. This critique illustrates the growing divergence between alchemical pharmaceutical theory (which posited genuine qualitative transformation through the magisterium concept) and emerging analytical chemistry (which sought to explain preparations in terms of mechanical and chemical composition). Lawrence Principe's work on the Boyle-alchemy nexus contextualizes this debate within seventeenth-century chemistry's transition away from alchemical philosophical frameworks.""",

"Liquor Potassae / Potassium Compounds": """Liquor Potassae (potassium hydroxide solution) and related potassium compounds occupied a significant position in early modern iatrochemical medicine and laboratory practice, representing the class of fixed alkalis derived from the calcination of plant materials. The name derives from 'pot ash'—the residue left in the pot after burning plant matter—and the term 'alkali' itself comes from the Arabic al-qali, the calcined ashes of the glasswort plant used in glass-making.

In Paracelsian iatrochemistry, the fixed alkalis (potash, soda, and related compounds) represented the Salt principle—the fixed, non-volatile residue that remains after the Mercury (volatile spirit) and Sulphur (combustible principle) have been driven off by calcination. This theoretical placement made potassium compounds central to the Paracelsian pharmaceutical system: as embodiments of the Salt principle, they were used in preparations aimed at conditions associated with Salt excess or deficiency, and as solvents for the preparation of other medicines.

Andreas Libavius's Alchemia (1597) and Johann Rudolf Glauber's Opera Omnia Chymica (1658–1661) both contain important discussions of alkali chemistry, including the preparation and properties of fixed alkalis from plant sources. Glauber's Sal Mirabile (sodium sulfate, now called Glauber's salt) was produced through the reaction of sulfuric acid with potassium or sodium salts, illustrating how iatrochemical research generated novel chemical substances through the systematic investigation of salt chemistry. The study of fixed and volatile alkalis, acids, and their reactions constitutes one of the major threads connecting early modern iatrochemistry to the emergence of modern inorganic chemistry in the late eighteenth century.""",

"Mercurius Duplicatus / Philosophical Mercury": """Mercurius Duplicatus (doubled or duplicated Mercury) is a technical alchemical concept designating Mercury in its doubled or self-multiplied form—Mercury that has been worked upon to increase its alchemical virtue and capacity for transformation. The concept draws on the broader alchemical understanding of Mercury as the principle of multiplication and projection: the philosopher's stone works by projecting its quality onto base metals in a process of indefinite multiplication, and the Mercury that serves as the vehicle for this projection must itself be prepared in a purified and multiplied form.

The term appears in the tradition of Hermetic philosophy associated with Hermes Trismegistus and the legend of the 'twice-great' or 'thrice-great' Hermes: the divine Mercury is doubly great because it encompasses both the celestial and terrestrial applications of the principle of communication and mediation. In alchemical laboratory context, Mercurius Duplicatus may designate specific preparations of mercury that have been subjected to multiple cycles of distillation, amalgamation, and sublimation—processes that alchemists believed could progressively purify and 'activate' mercury toward its philosophical perfection.

The concept connects to the broader Mercury symbolism that pervades Hermetic and alchemical thought: Mercury as messenger of the gods, as psychopomp (guide of souls), as the principle of linguistic and semiotic communication, and as the laboratory substance most capable of forming amalgams with other metals (acting thus as a universal mediator). Michael Maier's emblems in Atalanta Fugiens frequently deploy Mercury symbolism in both its mythological and laboratory dimensions, encoding through the winged messenger figure the theoretical status of Philosophical Mercury as the active, communicative principle that makes all alchemical transformation possible.""",

"Sulphur Principle / Philosophical Sulphur": """Philosophical Sulphur (Sulphur Philosophorum, also Sulphur Principle) designates the first of Paracelsus's three prime principles in its most systematic theoretical formulation—the universal principle of combustibility, warmth, soul, and fixed activity that pervades all natural substances. Distinguished from common sulfur (the yellow mineral) by its philosophical status as a universal principle rather than a specific substance, Philosophical Sulphur explains why things burn, why they are warm, why they have characteristic shapes and colors, and why they decay by oxidation rather than by mere desiccation.

The sulphur-mercury theory that underlies the tria prima has ancient Arabic roots in the work attributed to Jabir ibn Hayyan, where sulphur and mercury are the two fundamental principles from which all metals are composed in varying degrees of purity and proportion. Paracelsus's innovation was to add Salt as a third principle and to extend the triadic framework from metals to all natural substances—plants, animals, minerals, and human beings. This extended tria prima became the foundational framework of Paracelsian medicine and natural philosophy, shaping iatrochemistry through the seventeenth century.

In the alchemical symbolic system, Philosophical Sulphur corresponds to the sun, gold, the masculine fixed principle, and—in the emblematic literature—to the king who rules and generates in the philosophical marriage with the lunar Mercury-queen. Michael Maier's Atalanta Fugiens uses the mythological figure of Hippomenes (who throws the golden apples) as the solar-sulphurous principle; his pursuit of Atalanta (the volatile Mercury) and their eventual conjunction encodes the sulphur-mercury coniunctio that produces the philosopher's stone. William Newman and Lawrence Principe's concept of Decknamen explains how 'Philosophical Sulphur' can simultaneously designate the theoretical principle and specific laboratory substances—various forms of sulfur, red sulfide of mercury, or other substances—depending on the text and context.""",

"Salt / Philosophical Salt": """Philosophical Salt (Sal Philosophorum) is the third member of Paracelsus's tria prima, representing the principle of fixity, form, stability, and bodily embodiment in all natural substances. Where Philosophical Sulphur provides combustibility and soul, and Philosophical Mercury provides volatility and spirit, Philosophical Salt provides the fixed, material form that gives each substance its characteristic shape, taste, and resistance to change. It is the principle of crystallization, of material persistence, of the body's capacity to hold the soul and spirit together in a specific form.

The theological resonances of Salt are multiple and explicitly invoked by Paracelsus: salt as preservative (resisting decay), as covenant (the salt covenant of Leviticus), as wisdom ('you are the salt of the earth,' Matthew 5:13), and as the Eucharistic body (the material substrate that receives and embodies the spiritual). These resonances made Philosophical Salt a site of theological elaboration in Paracelsian and subsequent alchemical literature, connecting laboratory chemistry to Christian sacramental theology in ways that could be either orthodox or heterodox depending on the theological context.

The practical chemistry of Salt—the study of fixed alkalis, neutral salts, and their reactions with acids and volatile substances—became one of the most productive areas of early modern chemical research. Johann Rudolf Glauber's systematic study of salts, Johann Rudolph's Glauber's Opera Omnia, and later the work of Robert Boyle on the composition of various salts all drew on the Paracelsian Salt framework even as they progressively abandoned its cosmological elaborations. The transition from Philosophical Salt as a cosmic principle to 'salt' as a chemical category (the product of acid-base neutralization) is one of the most important conceptual transitions in the history of chemistry, and one that proceeded through the laboratory investigations of iatrochemists working within the Paracelsian tria prima framework.""",
}

TEXT_PATCHES = {
"Arcana or Mysteries of Love and Eloquence": """The Arcana or Mysteries of Love and Eloquence (c. 1658), attributed to 'A. Warren' and possibly connected to the wider circle of Hermetic writers active in mid-seventeenth-century England, belongs to the tradition of philosophical love literature that drew on Neoplatonic accounts of Eros as a cosmic and spiritual force. Such texts used the conventions of love poetry and courtly rhetoric to encode philosophical and sometimes alchemical content, following the tradition of the stil novo and the allegorical love poetry analyzed by Frances Yates in her work on Hermetic literature.

The tradition of 'courtly love' as philosophical allegory stretches from Ficino's commentary on Plato's Symposium—where he identifies heavenly Eros as the soul's upward-drawing principle—through the Renaissance Neoplatonic love treatises of Pietro Bembo, Baldassare Castiglione, and Leone Ebreo to the English reception in Sidney, Spenser, and their successors. In this tradition, the 'mysteries of love' are not merely erotic but philosophical: love as the soul's ascent toward beauty, truth, and the Good; eloquence as the verbal form through which this ascent is communicated and shared.

The 'arcana' dimension—the secret or initiatory character of the teaching—connects this text to the broader Rosicrucian and Hermetic tradition's claim that genuine knowledge is transmitted to the worthy through coded or allegorical vehicles. The mysteries of love, in this reading, are precisely the kind of graduated initiatory knowledge that the Invisible Brethren possess and transmit: accessible on a surface level to any reader of courtly literature, but revealing a deeper philosophical and spiritual teaching only to those prepared to receive it. This strategy of esoteric encoding within exoteric literary forms is central to the Hermetic tradition's literary production throughout the early modern period.""",

"The Golden Chain of Homer": """The Golden Chain of Homer (Aurea Catena Homeri, Frankfurt and Leipzig 1723), attributed to 'Anton Josef Kirchweger' in the first edition but probably a compilation by multiple authors associated with the Rosicrucian-influenced circles of late seventeenth and early eighteenth century Germany, is one of the most important documents of the transition between Renaissance Hermetism and eighteenth-century natural philosophy. The work presents a comprehensive natural philosophical system—a Hermetic cosmology of creation, generation, and dissolution—organized around the concept of the 'chain of nature' through which all substances are connected in a continuous hierarchy of generation.

The title refers to the golden chain by which Zeus suspends the cosmos in Homer's Iliad—an image that Neoplatonic commentators (Macrobius, Proclus) had interpreted as the chain of being connecting the divine to the material. The Golden Chain of Homer applies this image to natural philosophy: all substances are linked in a generative chain from the highest (fire, light) to the lowest (earth, matter), with each level generated from the one above and capable of dissolving back into it. This cosmological framework is explicitly alchemical: the circulation of niter (a universal seminal principle drawn from air) through the chain explains the generation of all natural substances, from rain and dew to metals and living organisms.

The work's influence on eighteenth-century natural philosophy has been documented by Principe and Newman: its 'niter' concept connects to the Sendivogian aerial niter tradition and to eighteenth-century phlogiston theory, suggesting that it represents an important node in the transmission of alchemical natural philosophy into early modern chemistry. Its circulation in Rosicrucian and Masonic circles in Germany and the Netherlands also documents the persistence of Hermetic natural philosophical ideas within esoteric institutional contexts well into the Enlightenment period.""",

"An Account of the Behmenists": """An Account of the Behmenists (c. 1697), most likely associated with the circle around Jane Lead and the Philadelphian Society, provides a contemporary description of the followers of Jacob Böhme active in England and the Netherlands in the late seventeenth century. The 'Behmenists' were communities of readers and practitioners who drew on Böhme's theosophy for both devotional and practical spiritual guidance, often in tension with or alongside their participation in mainstream Protestant churches.

The Philadelphian Society (founded c. 1694), centered on the prophetic writings of Jane Lead and the theological direction of Francis Lee, represents the most organized form of English Behmenism in the 1690s. Lead's Fountain of Gardens (1696–1701) and A Revelation of the Everlasting Gospel Message (1697) draw extensively on Böhme's spiritual-alchemical categories, particularly his accounts of divine Sophia (Wisdom) and the soul's union with her as the culmination of the spiritual life. The Philadelphians maintained that their community was the nucleus of the universal spiritual church that Böhme had prophesied.

Mike Zuber's research on the Behmenist tradition in England and Germany documents how these communities constituted themselves as bearers of a genuine spiritual-alchemical lineage: their devotional practices, their reading of Böhme's texts, and their mutual support were understood as stages in the Great Work of spiritual regeneration. The Account's significance lies in its contemporaneous documentation of this community as seen by either a sympathetic observer or a member. Ariel Hessayon's work on seventeenth-century English religious radicals situates the Behmenists within the broader landscape of dissenting spirituality, connecting them to earlier movements of spiritual-alchemical interpretation and forward to the eighteenth-century Pietist networks through which Böhme's influence continued to be transmitted.""",
}

with open(DB, encoding='utf-8') as f:
    db = json.load(f)

updates = 0
for fig in db['figures']:
    name = fig.get('name', '')
    if name in FIGURE_PATCHES:
        fig['essay'] = FIGURE_PATCHES[name].strip()
        updates += 1

for con in db['concepts']:
    name = con.get('name', '')
    if name in CONCEPT_PATCHES:
        con['essay'] = CONCEPT_PATCHES[name].strip()
        updates += 1

for txt in db['texts']:
    title = txt.get('title', '')
    if title in TEXT_PATCHES:
        txt['essay'] = TEXT_PATCHES[title].strip()
        updates += 1

with open(DB, 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print(f"Updated {updates} remaining entries")

# final verification
with open(DB, encoding='utf-8') as f:
    db2 = json.load(f)

for section, key in [('figures','name'), ('concepts','name'), ('texts','title')]:
    thin = [i for i in db2[section] if len(i.get('essay','') or '') < 800]
    print(f"{section}: {len(thin)} still thin")
    for i in thin:
        print(f"  {len(i.get('essay','') or ''):4d}  {i.get(key,'?')}")
